In [1]:
import numpy as np
import laser_hockey_env as lh
import gym
from importlib import reload

In [2]:
np.set_printoptions(suppress=True)

# Normal Game Play

In [25]:
reload(lh)

<module 'laser_hockey_env' from '/home/georg/src/python/laser-hockey-env/laser_hockey_env.py'>

In [26]:
env = lh.LaserHockeyEnv()

have a look at the initialization condition

In [27]:
obs = env.reset()
obs_agent2 = env.obs_agent_two()
env.render()

True

In [17]:
obs = env.reset()
obs_agent2 = env.obs_agent_two()

for _ in range(600):
    env.render()
    a1 = [1,-.5,0] # np.random.uniform(-1,1,3)
    a2 = [1,0.,0] # np.random.uniform(-1,1,3)*0    
    obs, r, d, info = env.step(np.hstack([a1,a2]))    
    obs_agent2 = env.obs_agent_two()
    if d: break

Without rendering, it runs much faster

In [19]:
obs = env.reset()
obs_agent2 = env.obs_agent_two()

for _ in range(600):    
    a1 = [1,-.5,0] # np.random.uniform(-1,1,3)
    a2 = [1,0.,0] # np.random.uniform(-1,1,3)*0    
    obs, r, d, info = env.step(np.hstack([a1,a2]))    
    obs_agent2 = env.obs_agent_two()
    if d: break

# Train Shooting

In [36]:
reload(lh)

<module 'laser_hockey_env' from '/home/georg/src/python/laser-hockey-env/laser_hockey_env.py'>

In [37]:
env = lh.LaserHockeyEnv(mode=lh.LaserHockeyEnv.TRAIN_SHOOTING)

In [38]:
o = env.reset()

In [39]:
env.render()

True

In [243]:
for _ in range(60):
    env.render()
    a1 = [1,0,0] # np.random.uniform(-1,1,3)
    a2 = [0,0.,0] 
    obs, r, d, info = env.step(np.hstack([a1,a2]))    
    obs_agent2 = env.obs_agent_two()
    if d: break

# Train DEFENDING

In [200]:
reload(lh)

<module 'envs.laser_hockey_env' from '/home/georg/src/python/laser-hockey-rl/envs/laser_hockey_env.py'>

In [221]:
env = lh.LaserHockeyEnv(mode=lh.LaserHockeyEnv.TRAIN_DEFENCE)

In [222]:
o = env.reset()

In [223]:
env.render()

True

In [225]:
for _ in range(60):
    env.render()
    a1 = [1,0,0] # np.random.uniform(-1,1,3)
    a2 = [0,0.,0] 
    obs, r, d, info = env.step(np.hstack([a1,a2]))    
    obs_agent2 = env.obs_agent_two()
    if d: break

# Using discrete actions

In [49]:
reload(lh)

<module 'laser_hockey_env' from '/home/georg/src/python/laser-hockey-env/laser_hockey_env.py'>

In [50]:
env = lh.LaserHockeyEnv(mode=lh.LaserHockeyEnv.TRAIN_SHOOTING)

In [51]:
import random

In [52]:
for _ in range(200):
    env.render()
    a1_discrete = random.randint(0,7)
    a1 = env.discrete_to_continous_action(a1_discrete)
    a2 = [0,0.,0] 
    obs, r, d, info = env.step(np.hstack([a1,a2]))    
    obs_agent2 = env.obs_agent_two()
    if d: break

# Hand-crafted Opponent

In [85]:
reload(lh)

<module 'laser_hockey_env' from '/home/georg/src/python/laser-hockey-env/laser_hockey_env.py'>

In [86]:
env = lh.LaserHockeyEnv(mode=lh.LaserHockeyEnv.TRAIN_DEFENCE)

In [87]:
o = env.reset()

In [88]:
env.render()

True

In [93]:
player1 = lh.BasicOpponent()
player2 = lh.BasicOpponent()

In [99]:
obs = env.reset()
obs_agent2 = env.obs_agent_two()
for _ in range(600):
    env.render()
    a1 = player1.act(obs)
    a2 = player2.act(obs_agent2)
    obs, r, d, info = env.step(np.hstack([a1,a2]))    
    obs_agent2 = env.obs_agent_two()
    if d: break

[-5.47181129  3.43619919  0.        ] [547.18112946 343.61991882   0.        ] [False False  True]
[-5.45844746 -2.10290718  0.        ] [8.29322179 3.10080166 0.        ] [False False  True]
[-5.43198776 -2.10263968  0.        ] [  4.13708146 625.11139188   0.        ] [False False  True]
[-5.39269352 -2.08901405  0.        ] [2.75880376 3.1119949  0.        ] [False False  True]
[-5.34082127 -2.06229734  0.        ] [2.06719421 1.55547131 0.        ] [False False  True]
[-5.27662277 -2.02275133  0.        ] [1.64898661 1.0281868  0.        ] [False False  True]
[-5.20034504 -1.97063255  0.        ] [1.36710808 0.75912236 0.        ] [False False  True]
[-5.11222935 -1.90619278  0.        ] [1.16297895 0.59346001 0.        ] [False False  True]
[-5.01251221 -1.82967806  0.        ] [1.00736371 0.47950801 0.        ] [False False  True]
[-4.90142536 -1.74133015  0.        ] [0.88404197 0.39509175 0.        ] [False False  True]
[-4.77919674 -1.64138556  0.        ] [0.78329117 0.329116

[-2.93820858  0.11220598  1.02332163] [0.6370893  0.01603299 0.64814072] [False  True  True]
[-2.83121777 -0.01319361  1.05332518] [0.54575914 0.00213127 0.7068464 ] [False  True  True]
[-2.71307373 -0.12256813  1.08155501] [0.47168325 0.02270326 0.77171588] [False  True  True]
[-2.58401394 -0.21624756  1.10801125] [0.40984599 0.04677902 0.84399836] [False  True  True]
[-2.44426823 -0.29455662  1.13269389] [0.3569981  0.07626436 0.92530494] [False  True  True]
[-2.29406166 -0.3578124   1.15560281] [0.31094227 0.11479081 1.01774992] [False False False]
[-2.13361549 -0.40632486  1.17673814] [0.27013947 0.17024126 1.12416436] [False False False]
[-1.96314144 -0.44039869  1.19609988] [0.2334789  0.26354734 1.24842727] [False False False]
[-1.78285027 -0.46033096  1.2136879 ] [0.20013956 0.47474445 1.39600036] [False False False]
[ 9.66290827 -4.95561387  1.02134196] [ 1.02820338 17.5566051   1.30820172] [False False False]
[ 9.36962004 -4.10897765  1.11740035] [ 1.09695016 10.49916973  1.6